language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TOKEN
  local_dir: build
  on:
    branch: master
